export const questions = [
    "Wat zijn de activiteiten waar je helemaal in opgaat en de tijd uit het oog verliest?",
    "Als geld geen rol speelde, hoe zou je je tijd dan het liefst besteden?",
    "Welke prestaties in je leven maken je het meest trots?",
    "Welke dromen had je als kind die je nog niet hebt waargemaakt?",
    "Als je terugkijkt op je leven, welke momenten hebben je het meest gelukkig gemaakt?",
    "Welke vaardigheden wil je graag ontwikkelen of verbeteren?",
    "Wat zijn je favoriete onderwerpen om over te praten of te lezen?",
    "Welke waarden zijn het belangrijkst voor jou in het leven?",
    "Welke mensen inspireren je en waarom?",
    "Als je een week de tijd had om vrijwilligerswerk te doen, welke organisatie zou je dan kiezen?",
    "Wat zijn je favoriete manieren om te ontspannen en tot rust te komen?",
    "Welke reisbestemmingen staan bovenaan je verlanglijstje en waarom?",
    "Wat zou je doen als je wist dat je niet kon falen?",
    "Welke uitdagingen of problemen in de wereld raken je het meest?",
    "Wat zijn je favoriete eigenschappen in andere mensen?",
    "Als je slechts één doel zou kunnen bereiken in je leven, wat zou dat dan zijn?",
    "Welke activiteiten geven je een gevoel van voldoening en vervulling?",
    "Welke rol spelen familie en vrienden in jouw geluk?",
    "Wat zijn je grootste angsten en hoe beïnvloeden ze je keuzes?",
    "Welke boeken, films of kunstwerken hebben een blijvende indruk op je gemaakt?",
    "Als je een superkracht zou kunnen hebben, welke zou je dan kiezen en waarom?",
    "Wat zijn je favoriete manieren om nieuwe dingen te leren?",
    "Hoe zou je je ideale werkdag omschrijven?",
    "Wat zijn je favoriete herinneringen uit je jeugd?",
    "Welke doelen wil je bereiken op persoonlijk, professioneel en spiritueel gebied?",
    "Wat zijn je grootste successen tot nu toe en wat heb je ervan geleerd?",
    "Hoe zou je willen dat mensen je herinneren als je er niet meer bent?",
    "Welke maatschappelijke kwesties vind je belangrijk en waarom?",
    "Als je een mentor zou kunnen hebben, wie zou dat dan zijn en waarom?",
    "Welke gewoonten wil je graag ontwikkelen of veranderen?",
    "Hoe belangrijk is balans tussen werk en privé voor jou?",
    "Wat zijn je favoriete manieren om met stress om te gaan?",
    "Als je terug kon gaan in de tijd, wat zou je dan anders doen?",
    "Welke levenslessen heb je tot nu toe geleerd?",
    "Hoe zie je jezelf over vijf jaar, tien jaar, en wat wil je hebben bereikt?",
    "Welke activiteiten geven je energie en welke kosten je energie?",
    "Wat zijn je favoriete manieren om anderen te helpen?",
    "Hoe belangrijk is het voor jou om een positieve impact te hebben op de wereld?",
    "Welke risico's ben je bereid te nemen om je doelen te bereiken?",
    "Wat betekent geluk voor jou en hoe denk je dat je het kunt bereiken?",
    "Als je onbeperkte middelen en tijd had, welke projecten zou je dan ondernemen?",
    "Wat zou je doen als je een jaar lang verlof zou nemen zonder zorgen over geld?",
    "Welke eigenschappen bewonder je het meest bij anderen?",
    "Als je een boodschap kon doorgeven aan de hele wereld, wat zou die boodschap dan zijn?",
    "Hoe ziet jouw ideale ochtendroutine eruit?",
    "Welke plaatsen op aarde zou je willen bezoeken en waarom?",
    "Als je een nieuwe vaardigheid zou kunnen leren in een week, welke zou dat dan zijn?",
    "Wat motiveert je om 's ochtends uit bed te komen?",
    "Welke rol speelt gezondheid in jouw leven en wat zou je willen verbeteren?",
    "Welke levenservaringen hebben je het meest gevormd?",
    "Wat betekent succes voor jou persoonlijk?",
    "Hoe zou je jezelf omschrijven aan iemand die je niet kent?",
    "Welke hobbies of passies heb je verwaarloosd en zou je willen oppakken?",
    "Welke mensen in je leven geven je energie en welke kosten je energie?",
    "Hoe belangrijk is het voor jou om een verschil te maken in de levens van anderen?",
    "Wat is je favoriete manier om creatief uitdrukking te geven?",
    "Wat zijn je favoriete boeken, films of muziek en waarom spreken ze je aan?",
    "Welke gewoonten zou je willen ontwikkelen om een gezonder leven te leiden?",
    "Wat zijn je grootste twijfels of angsten over de toekomst?",
    "Hoe ziet jouw ideale vakantie eruit?",
    "Welke eigenschappen waardeer je het meest in een levenspartner?",
    "Wat zou je willen veranderen aan de wereld als je de macht had?",
    "Welke doelen wil je bereiken op sociaal gebied, zoals vriendschappen en relaties?",
    "Hoe ga je om met tegenslagen en moeilijke tijden?",
    "Wat zijn je favoriete manieren om te ontspannen na een drukke dag?",
    "Hoe belangrijk is het voor jou om een gezonde werk-privébalans te behouden?",
    "Als je slechts één levensles zou kunnen doorgeven aan anderen, wat zou dat dan zijn?",
    "Welke onvervulde verlangens heb je op dit moment?",
    "Hoe zie je jezelf groeien op spiritueel gebied?",
    "Wat zijn je favoriete manieren om zelfreflectie te beoefenen?",
    "Hoe ziet jouw perfecte weekend eruit?",
    "Welke films of boeken hebben je kijk op het leven veranderd?",
    "Wat zijn je grootste prestaties tot nu toe en waarom zijn ze belangrijk voor jou?",
    "Wat is je favoriete manier om terug in contact te komen met de natuur?",
    "Hoe belangrijk is het voor jou om betrokken te zijn bij je gemeenschap?",
    "Als je één superkracht zou kunnen hebben, wat zou je dan kiezen en waarom?",
    "Welke gewoonten zou je willen doorgeven aan toekomstige generaties?",
    "Hoe denk je dat je een positieve impact kunt hebben op de wereld?",
    "Wat zijn je favoriete manieren om nieuwe mensen te ontmoeten?",
    "Als je terug kon gaan in de tijd, welke adviezen zou je aan je jongere zelf geven?",
    "Wat is je favoriete manier om jezelf uit te dagen en te groeien?",
    "Welke plaatsen voelen als thuis voor jou en waarom?",
    "Wat zijn je favoriete manieren om jezelf te uiten?",
    "Als je een doel zou kunnen bereiken in de komende maand, wat zou dat dan zijn?",
    "Welke levensfilosofie volg je en waarom spreekt die je aan?",
    "Hoe ziet jouw ideale werkomgeving eruit?",
    "Wat zijn je favoriete manieren om jezelf te inspireren als je vastloopt?",
    "Hoe denk je over geld en welke rol speelt het in jouw leven?",
    "Wat betekent geluk voor jou op de lange termijn?",
    "Hoe belangrijk is het voor jou om te blijven leren en groeien?",
    "Wat zijn je favoriete manieren om anderen te helpen zonder iets terug te verwachten?",
    "Hoe zorg je voor een goede balans tussen persoonlijke groei en acceptatie van jezelf?",
    "Welke reis heeft de meeste invloed gehad op jouw kijk op het leven?",
    "Hoe zou je jezelf uitdrukken als je alle beperkingen zou kunnen overwinnen?",
    "Welke adviezen heb je gekregen die je altijd bijblijven?",
    "Wat zijn je grootste ambities op professioneel gebied?",
    "Hoe ziet jouw ideale levensstijl eruit?",
    "Welke activiteiten brengen je in een staat van flow, waar alles vanzelf lijkt te gaan?",
    "Wat zijn je favoriete manieren om te genieten van het moment?",
    "Als je een boodschap zou kunnen sturen naar je toekomstige zelf, wat zou die boodschap dan zijn?Wat zijn de activiteiten waar je van nature naar toe getrokken wordt?",
    "Welke dromen had je als kind die nog steeds resoneren met je?",
    "Welke bezigheden geven je een gevoel van opwinding en voldoening?",
    "Als je een week lang niets hoefde te doen voor geld, hoe zou je die tijd dan besteden?",
    "Welke onderwerpen lees je graag over in je vrije tijd?",
    "Als geld en opleiding geen beperkingen waren, welk beroep zou je dan uitoefenen?",
    "Wat zijn de vaardigheden waarvan je denkt dat je ze van nature bezit?",
    "Welke complimenten ontvang je vaak van anderen over je capaciteiten?",
    "Wat zou je doen als je wist dat je niet kon falen?",
    "Welke activiteiten brengen je in een staat van flow, waar de tijd voorbij vliegt?",
    "Hoe voel je je wanneer je anderen helpt of een positieve impact hebt?",
    "Welke films, boeken of verhalen inspireren je en waarom?",
    "Wat zijn de thema's die steeds weer terugkomen in je interesses?",
    "Als je een doel zou kunnen kiezen om de rest van je leven aan te werken, wat zou dat dan zijn?",
    "Welke activiteiten zou je willen proberen, zelfs als je denkt dat je er nu niet goed in bent?",
    "Hoe zien je ideale werkomgeving en werkdag eruit?",
    "Welke momenten in je leven hebben je het meest gepassioneerd gemaakt?",
    "Als je met één persoon kon samenwerken, wie zou dat dan zijn en waarom?",
    "Hoe belangrijk is het voor jou om creativiteit uit te drukken in wat je doet?",
    "Welke problemen in de wereld raken je het meest en zou je willen helpen oplossen?",
    "Hoe zou je jezelf zien bijdragen aan de gemeenschap of de samenleving als geheel?",
    "Wat zijn je favoriete hobby's en waarom geniet je ervan?",
    "Als je een dag zou kunnen doorbrengen met iemand die je bewondert, wat zouden jullie dan doen?",
    "Wat zijn je favoriete herinneringen waarin je je levendig en betrokken voelde?",
    "Welke aspecten van je huidige werk of activiteiten vind je het meest vervullend?",
    "Als je een jaar de tijd had om iets nieuws te leren, wat zou je dan kiezen?",
    "Hoe reageer je op uitdagingen en obstakels in je leven?",
    "Wat zijn je persoonlijke waarden en hoe weerspiegelen ze je passies?",
    "Hoe zou je willen bijdragen aan het welzijn van anderen?",
    "Wat zijn je grootste angsten met betrekking tot het volgen van je passie?",
    "Welke rol speelt persoonlijke groei in je zoektocht naar passie?",
    "Hoe belangrijk is het voor jou om een balans te vinden tussen werk en privéleven?",
    "Als je kon kiezen, waar in de wereld zou je dan willen wonen en waarom?",
    "Welke talenten bewonder je bij anderen en zou je zelf willen ontwikkelen?",
    "Hoe ziet je ideale vrije dag eruit, zonder verplichtingen?",
    "Wat zijn de onderwerpen waarover je graag praat met anderen?",
    "Als je mocht deelnemen aan een project zonder beperkingen, wat zou dat dan zijn?",
    "Hoe belangrijk is het voor jou om een positieve impact te hebben op de wereld?",
    "Welke adviezen zou je jezelf geven als je terugkijkt op je leven tot nu toe?",
    "Welke nieuwe activiteiten zou je willen proberen om je horizon te verbreden?",
    "Welke doelen zou je jezelf stellen als tijd en geld geen beperkingen waren?",
    "Wat zijn je favoriete manieren om jezelf te inspireren als je vastzit?",
    "Hoe zou je jezelf omschrijven aan anderen zonder te verwijzen naar je werk of studie?",
    "Wat zijn je favoriete manieren om je creativiteit te stimuleren?",
    "Als je een boodschap zou willen doorgeven aan toekomstige generaties, wat zou die dan zijn?",
    "Hoe belangrijk is het voor jou om je passie te delen met anderen?",
    "Wat zijn je favoriete manieren om te reflecteren op je eigen leven en doelen?",
    "Hoe zou je jezelf zien groeien op persoonlijk en professioneel gebied?",
    "Welke stap kun je vandaag zetten om dichter bij je passie te komen?",
    "Wat betekent het voor jou om een betekenisvol leven te leiden?"
];